#!/bin/bash


if [ $# -eq 0 ]
 then
	echo "No filename.  usage: ./build <filename>"
	exit 1
fi

FILE=$1
EXT="${FILE##*.}"
NAME="${FILE%.*}"

echo " Building $FILE as $NAME... "

EXISTING=`ls | grep -v $FILE | grep $NAME`

if [ -n "$EXISTING" ]
then
	rm $NAME
fi

if [ "$EXT" != "c" ]
then
	echo "filename extension $EXT should be c.  exiting"
	exit 1;
fi

gcc $FILE -o $NAME
