#!/bin/bash


if [ $# -eq 0 ]
 then
	echo "No filename.  usage: ./build <filename>"
	exit 1
fi

FILE=$1
EXT="${FILE##*.}"
NAME="${FILE%.*}"

echo " \033[33m Building $FILE as $NAME... \033[10m"

EXISTING=`ls | grep -v $FILE | grep $NAME`

if [ -n "$EXISTING" ]
then
	rm $NAME
fi

if [ "$EXT" != "cpp" ]
then
	echo "filename extension $EXT should be cpp.  exiting"
	exit 1;
fi

g++ $FILE -o $NAME

